spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:kreativstorrm
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss



